### ISSUE TITLE
Problem with enable autowatch

### ISSUE THREAD

**Issue by psike01** [MatthewPaulGithub/redmine_im_link#1]
Hi!
It doesn't work with version 4.0.4.stable
If you try make new issue, and assign user - it will crash, with error "Watchers is invalid"
In logs:
_Parameters: {"utf8"=>"✓", "authenticity_token"=>"Vc04yOzbC6cPGklEN5cotxnXkx7i3qRd+X9VcysTcrk3JtDb6ommPRqUlBH13E2AAHqGQGCcfyGd9QlCl0sOgQ==", "form_update_triggered_by"=>"", "issue"=>{"is_private"=>"0", "tracker_id"=>"8", "subject"=>"TEST", "description"=>"", "status_id"=>"6", "priority_id"=>"2", "assigned_to_id"=>"777", "fixed_version_id"=>"", "parent_issue_id"=>"", "start_date"=>"2019-08-28", "due_date"=>"", "estimated_hours"=>"", "done_ratio"=>"0", "custom_field_values"=>{"79"=>"", "13"=>"", "62"=>"", "83"=>"", "84"=>""}, "watcher_user_ids"=>["", "4", "927"]}, "commit"=>"Make", "project_id"=>"utm-level3-ckp-okp"}_

I think, trouble in this^
**watcher_user_ids"=>["", "4", "927"]**

**Comment by gainskills** [comment]
Not sure my issue is same to this issue, I met a similar issue, copy the logs here

- The reason might be: the ticket is from an anonymous user with the option: 'Enable Author/Assignee section' enabled.

- with autowatcher option
```
redmine_1     | I, [2020-01-03T04:45:17.860931 #1]  INFO -- : Completed 500 Internal Server Error in 326ms (ActiveRecord: 56.5ms)
redmine_1     | F, [2020-01-03T04:45:17.861504 #1] FATAL -- :   
redmine_1     | F, [2020-01-03T04:45:17.861531 #1] FATAL -- : ActionView::Template::Error (undefined method `downcase' for nil:NilClass):
redmine_1     | F, [2020-01-03T04:45:17.861598 #1] FATAL -- :      9: 
redmine_1     |     10: <h3><%= l(:label_issue_watchers) %> (<%= watched.watcher_users.size %>)</h3>
redmine_1     |     11: 
redmine_1     |     12: <%= watchers_list(watched) %>
redmine_1     | F, [2020-01-03T04:45:17.861620 #1] FATAL -- :   
redmine_1     | F, [2020-01-03T04:45:17.861644 #1] FATAL -- : plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:41:in `block in build_im_link'
redmine_1     | plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:41:in `any?'
redmine_1     | plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:41:in `build_im_link'
redmine_1     | plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:55:in `buildlink1'
redmine_1     | plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:156:in `watchers_list_with_im_link'
redmine_1     | app/views/watchers/_watchers.html.erb:12:in `_app_views_watchers__watchers_html_erb__2663953056542160905_46973589121540'
redmine_1     | app/views/issues/show.html.erb:144:in `block in _app_views_issues_show_html_erb___4013550653517130180_46973548316740'
redmine_1     | app/views/issues/show.html.erb:138:in `_app_views_issues_show_html_erb___4013550653517130180_46973548316740'
redmine_1     | app/controllers/issues_controller.rb:107:in `block (2 levels) in show'
redmine_1     | app/controllers/issues_controller.rb:99:in `show'
redmine_1     | lib/redmine/sudo_mode.rb:65:in `sudo_mode'
redmine_1     | 172.24.0.1 - - [03/Jan/2020:04:45:17 UTC] "GET /issues/274 HTTP/1.1" 500 648
redmine_1     | http://127.0.0.1/projects/itsupport/issues -> /issues/274
```

- without auto watcher option

```
redmine_1     | 172.24.0.1 - - [03/Jan/2020:04:49:18 UTC] "GET /issues/274 HTTP/1.1" 500 648
redmine_1     | http://127.0.0.1/projects/itsupport/issues -> /issues/274
redmine_1     | I, [2020-01-03T04:46:58.174884 #1]  INFO -- :   Parameters: {"id"=>"274"}
redmine_1     | I, [2020-01-03T04:46:58.189644 #1]  INFO -- :   Current user: admin (id=1)
redmine_1     | I, [2020-01-03T04:46:58.222872 #1]  INFO -- :   Rendering issues/show.html.erb within layouts/base
redmine_1     | I, [2020-01-03T04:46:58.225369 #1]  INFO -- :   Rendered issues/_action_menu.html.erb (2.3ms)
redmine_1     | I, [2020-01-03T04:46:58.263647 #1]  INFO -- :   Rendered plugins/custom_tables/app/views/issues/_custom_tables.html.erb (2.5ms)
redmine_1     | I, [2020-01-03T04:46:58.266137 #1]  INFO -- :   Rendered issue_relations/_form.html.erb (1.6ms)
redmine_1     | I, [2020-01-03T04:46:58.266256 #1]  INFO -- :   Rendered issues/_relations.html.erb (1.9ms)
redmine_1     | I, [2020-01-03T04:46:58.267598 #1]  INFO -- :   Rendered issues/_action_menu.html.erb (1.1ms)
redmine_1     | I, [2020-01-03T04:46:58.273361 #1]  INFO -- :   Rendered issues/_trackers_description.html.erb (0.3ms)
redmine_1     | I, [2020-01-03T04:46:58.288392 #1]  INFO -- :   Rendered issues/_form_custom_fields.html.erb (0.2ms)
redmine_1     | I, [2020-01-03T04:46:58.288459 #1]  INFO -- :   Rendered issues/_attributes.html.erb (14.0ms)
redmine_1     | I, [2020-01-03T04:46:58.288579 #1]  INFO -- :   Rendered issues/_form.html.erb (20.6ms)
redmine_1     | I, [2020-01-03T04:46:58.296814 #1]  INFO -- :   Rendered attachments/_form.html.erb (1.8ms)
redmine_1     | I, [2020-01-03T04:46:58.298139 #1]  INFO -- :   Rendered issues/_edit.html.erb (30.4ms)
redmine_1     | I, [2020-01-03T04:46:58.298207 #1]  INFO -- :   Rendered issues/_action_menu_edit.html.erb (31.8ms)
redmine_1     | I, [2020-01-03T04:46:58.300929 #1]  INFO -- :   Rendered issues/_sidebar.html.erb (1.3ms)
redmine_1     | I, [2020-01-03T04:46:58.311053 #1]  INFO -- :   Rendered watchers/_watchers.html.erb (10.0ms)
redmine_1     | I, [2020-01-03T04:46:58.311132 #1]  INFO -- :   Rendered issues/show.html.erb within layouts/base (88.2ms)
redmine_1     | I, [2020-01-03T04:46:58.311275 #1]  INFO -- : Completed 500 Internal Server Error in 136ms (ActiveRecord: 40.0ms)
redmine_1     | F, [2020-01-03T04:46:58.311850 #1] FATAL -- :   
redmine_1     | F, [2020-01-03T04:46:58.311877 #1] FATAL -- : ActionView::Template::Error (undefined method `downcase' for nil:NilClass):
redmine_1     | F, [2020-01-03T04:46:58.311941 #1] FATAL -- :      9: 
redmine_1     |     10: <h3><%= l(:label_issue_watchers) %> (<%= watched.watcher_users.size %>)</h3>
redmine_1     |     11: 
redmine_1     |     12: <%= watchers_list(watched) %>
redmine_1     | F, [2020-01-03T04:46:58.311963 #1] FATAL -- :   
redmine_1     | F, [2020-01-03T04:46:58.311986 #1] FATAL -- : plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:41:in `block in build_im_link'
redmine_1     | plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:41:in `any?'
redmine_1     | plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:41:in `build_im_link'
redmine_1     | plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:55:in `buildlink1'
redmine_1     | plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:156:in `watchers_list_with_im_link'
redmine_1     | app/views/watchers/_watchers.html.erb:12:in `_app_views_watchers__watchers_html_erb__2663953056542160905_46973589121540'
redmine_1     | app/views/issues/show.html.erb:144:in `block in _app_views_issues_show_html_erb___4013550653517130180_46973548316740'
redmine_1     | app/views/issues/show.html.erb:138:in `_app_views_issues_show_html_erb___4013550653517130180_46973548316740'
redmine_1     | app/controllers/issues_controller.rb:107:in `block (2 levels) in show'
redmine_1     | app/controllers/issues_controller.rb:99:in `show'
redmine_1     | lib/redmine/sudo_mode.rb:65:in `sudo_mode'
redmine_1     | I, [2020-01-03T04:49:18.033652 #1]  INFO -- : Started GET "/issues/274" for 172.24.0.1 at 2020-01-03 04:49:18 +0000
redmine_1     | I, [2020-01-03T04:49:18.034296 #1]  INFO -- : Processing by IssuesController#show as HTML
redmine_1     | I, [2020-01-03T04:49:18.034341 #1]  INFO -- :   Parameters: {"id"=>"274"}
redmine_1     | I, [2020-01-03T04:49:18.041522 #1]  INFO -- :   Current user: admin (id=1)
redmine_1     | I, [2020-01-03T04:49:18.083841 #1]  INFO -- :   Rendering issues/show.html.erb within layouts/base
redmine_1     | I, [2020-01-03T04:49:18.086527 #1]  INFO -- :   Rendered issues/_action_menu.html.erb (2.5ms)
redmine_1     | I, [2020-01-03T04:49:18.132489 #1]  INFO -- :   Rendered plugins/custom_tables/app/views/issues/_custom_tables.html.erb (3.8ms)
redmine_1     | I, [2020-01-03T04:49:18.134341 #1]  INFO -- :   Rendered issue_relations/_form.html.erb (0.7ms)
redmine_1     | I, [2020-01-03T04:49:18.134476 #1]  INFO -- :   Rendered issues/_relations.html.erb (1.2ms)
redmine_1     | I, [2020-01-03T04:49:18.136030 #1]  INFO -- :   Rendered issues/_action_menu.html.erb (1.3ms)
redmine_1     | I, [2020-01-03T04:49:18.143999 #1]  INFO -- :   Rendered issues/_trackers_description.html.erb (0.6ms)
redmine_1     | I, [2020-01-03T04:49:18.161846 #1]  INFO -- :   Rendered issues/_form_custom_fields.html.erb (0.4ms)
redmine_1     | I, [2020-01-03T04:49:18.161986 #1]  INFO -- :   Rendered issues/_attributes.html.erb (16.1ms)
redmine_1     | I, [2020-01-03T04:49:18.162187 #1]  INFO -- :   Rendered issues/_form.html.erb (25.7ms)
redmine_1     | I, [2020-01-03T04:49:18.174265 #1]  INFO -- :   Rendered attachments/_form.html.erb (1.1ms)
redmine_1     | I, [2020-01-03T04:49:18.175905 #1]  INFO -- :   Rendered issues/_edit.html.erb (39.7ms)
redmine_1     | I, [2020-01-03T04:49:18.175976 #1]  INFO -- :   Rendered issues/_action_menu_edit.html.erb (41.3ms)
redmine_1     | I, [2020-01-03T04:49:18.181326 #1]  INFO -- :   Rendered issues/_sidebar.html.erb (2.5ms)
redmine_1     | I, [2020-01-03T04:49:18.194314 #1]  INFO -- :   Rendered watchers/_watchers.html.erb (12.7ms)
redmine_1     | I, [2020-01-03T04:49:18.194485 #1]  INFO -- :   Rendered issues/show.html.erb within layouts/base (110.5ms)
redmine_1     | I, [2020-01-03T04:49:18.194725 #1]  INFO -- : Completed 500 Internal Server Error in 160ms (ActiveRecord: 45.8ms)
redmine_1     | F, [2020-01-03T04:49:18.195407 #1] FATAL -- :   
redmine_1     | F, [2020-01-03T04:49:18.195444 #1] FATAL -- : ActionView::Template::Error (undefined method `downcase' for nil:NilClass):
redmine_1     | F, [2020-01-03T04:49:18.195535 #1] FATAL -- :      9: 
redmine_1     |     10: <h3><%= l(:label_issue_watchers) %> (<%= watched.watcher_users.size %>)</h3>
redmine_1     |     11: 
redmine_1     |     12: <%= watchers_list(watched) %>
redmine_1     | F, [2020-01-03T04:49:18.195571 #1] FATAL -- :   
redmine_1     | F, [2020-01-03T04:49:18.195596 #1] FATAL -- : plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:41:in `block in build_im_link'
redmine_1     | plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:41:in `any?'
redmine_1     | plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:41:in `build_im_link'
redmine_1     | plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:55:in `buildlink1'
redmine_1     | plugins/redmine_im_link/lib/redmine_im_link_watchers_patch.rb:156:in `watchers_list_with_im_link'
redmine_1     | app/views/watchers/_watchers.html.erb:12:in `_app_views_watchers__watchers_html_erb__2663953056542160905_46973589121540'
redmine_1     | app/views/issues/show.html.erb:144:in `block in _app_views_issues_show_html_erb___4013550653517130180_46973548316740'
redmine_1     | app/views/issues/show.html.erb:138:in `_app_views_issues_show_html_erb___4013550653517130180_46973548316740'
redmine_1     | app/controllers/issues_controller.rb:107:in `block (2 levels) in show'
redmine_1     | app/controllers/issues_controller.rb:99:in `show'
redmine_1     | lib/redmine/sudo_mode.rb:65:in `sudo_mode'
redmine_1     | I, [2020-01-03T04:49:26.695608 #1]  INFO -- : Started GET "/issues/274" for 172.24.0.1 at 2020-01-03 04:49:26 +0000
redmine_1     | I, [2020-01-03T04:49:26.696229 #1]  INFO -- : Processing by IssuesController#show as HTML
redmine_1     | I, [2020-01-03T04:49:26.696269 #1]  INFO -- :   Parameters: {"id"=>"274"}
redmine_1     | I, [2020-01-03T04:49:26.701639 #1]  INFO -- :   Current user: admin (id=1)
redmine_1     | I, [2020-01-03T04:49:26.731932 #1]  INFO -- :   Rendering issues/show.html.erb within layouts/base
redmine_1     | I, [2020-01-03T04:49:26.734853 #1]  INFO -- :   Rendered issues/_action_menu.html.erb (2.7ms)
redmine_1     | I, [2020-01-03T04:49:26.769733 #1]  INFO -- :   Rendered plugins/custom_tables/app/views/issues/_custom_tables.html.erb (2.4ms)
redmine_1     | I, [2020-01-03T04:49:26.771255 #1]  INFO -- :   Rendered issue_relations/_form.html.erb (0.7ms)
redmine_1     | I, [2020-01-03T04:49:26.771370 #1]  INFO -- :   Rendered issues/_relations.html.erb (1.0ms)
redmine_1     | I, [2020-01-03T04:49:26.772780 #1]  INFO -- :   Rendered issues/_action_menu.html.erb (1.2ms)
redmine_1     | I, [2020-01-03T04:49:26.778437 #1]  INFO -- :   Rendered issues/_trackers_description.html.erb (0.3ms)
redmine_1     | I, [2020-01-03T04:49:26.791929 #1]  INFO -- :   Rendered issues/_form_custom_fields.html.erb (0.2ms)
redmine_1     | I, [2020-01-03T04:49:26.792003 #1]  INFO -- :   Rendered issues/_attributes.html.erb (12.4ms)
redmine_1     | I, [2020-01-03T04:49:26.792107 #1]  INFO -- :   Rendered issues/_form.html.erb (19.0ms)
redmine_1     | I, [2020-01-03T04:49:26.799860 #1]  INFO -- :   Rendered attachments/_form.html.erb (0.9ms)
redmine_1     | I, [2020-01-03T04:49:26.801166 #1]  INFO -- :   Rendered issues/_edit.html.erb (28.2ms)
redmine_1     | I, [2020-01-03T04:49:26.801229 #1]  INFO -- :   Rendered issues/_action_menu_edit.html.erb (29.7ms)
redmine_1     | 172.24.0.1 - - [03/Jan/2020:04:49:26 UTC] "GET /issues/274 HTTP/1.1" 500 648
redmine_1     | http://127.0.0.1/projects/itsupport/issues -> /issues/274
```
